accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('singup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

pairpjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('reviews.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
  pass

reviews/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings

# Create your models here.

class Review(models.Model):
  user = models.ForeignKey(settings.AUTH_USER_MODEL,
                           on_delete=models.CASCADE)
  title = models.CharField(max_length=80)
  content = models.TextField()
  movie_name = models.CharField(max_length=30)
  grade = models.FloatField(validators=[MinValueValidator(0.0), MaxValueValidator(5.0)],)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  image = ProcessedImageField(upload_to='images/', blank=True,
                                processors=[ResizeToFill(500, 400)],
                                format='JPEG',
                                options={'quality': 60})

class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                           on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
  
  class Meta:
    model = get_user_model()
    fields = ('username', 'password1', 'password2', 'email', )

reviews/forms.py
from django import forms
from .models import Review, Comment

class ReviewForm(forms.ModelForm):
  
  class Meta:
    model = Review
    fields = ['title', 'movie_name', 'grade', 'content', 'image', ]
  
class CommentForm(forms.ModelForm):
  
  class Meta:
    model = Comment
    fields = ['content', ]

accounts/views.py
from django.shortcuts import render, redirect
# forms.py에서 가져오는 form
from .forms import CustomUserCreationForm
# 내장form에서 가져오는 form
from django.contrib.auth.forms import AuthenticationForm
# login인증 기능 모듈
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
# Create your views here.
def index(request):
  return render(request, 'accounts/index.html')

def signup(request):
  if request.method == 'POST':
    form = CustomUserCreationForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('accounts:index')
  else:
    form = CustomUserCreationForm
    context = {
      'form': form,
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
  if request.method == 'POST':
    form = AuthenticationForm(request, data=request.POST)
    if form.is_valid():
      auth_login(request, form.get_user())
      return redirect(request.GET.get('next') or 'reviews:index')
  else:
    form = AuthenticationForm
  context = {
    'form': form
  }
  return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:index')

reviews/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from .models import Review, Comment
from .forms import ReviewForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.

def index(request):
  review = Review.objects.all().order_by('-pk')
  context = {
    'reviews': review,
  }
  return render(request, 'reviews/index.html', context)

@login_required
def create(request):
    if request.user.is_authenticated:
      if request.method == 'POST':
        review_form = ReviewForm(request.POST, request.FILES)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('reviews:index')
      else:
        review_form = ReviewForm()
      context = {
        'review_form': review_form,
      }
      return render(request, 'reviews/create.html', context=context)
    else:
      return redirect('accounts:login')

def detail(request, pk):
  # 특정 글을 가져온다.
  review = Review.objects.get(pk=pk)
  comment_form = CommentForm()
  context = {
    'review': review,
    'comments' : review.comment_set.all(),
    'comment_form': comment_form,   
  }
  return render(request, 'reviews/detail.html', context)

@login_required
def update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.user == review.user:
      if request.method == 'POST':
          # POST : input 값 가져와서, 검증하고, DB에 저장
          review_form = ReviewForm(request.POST, request.FILES, instance=review)
          if review_form.is_valid():
              # 유효성 검사 통과하면 저장하고, 상세보기 페이지로
              review_form.save()
              messages.success(request, '글이 수정되었습니다.')
              return redirect('reviews:detail', review.pk)
          # 유효성 검사 통과하지 않으면 => context 부터해서 오류메시지 담긴 review_form을 랜더링
      else:
          # GET : Form을 제공
          review_form = ReviewForm(instance=review)
      context = {
          'review_form': review_form
      }
      return render(request, 'reviews/update.html', context)
    else:
      messages.warning(request, '작성자만 수정할 수 있습니다.')
      return redirect('reviews.detail', review.pk)

def delete(request, pk):
    Review.objects.get(id=pk).delete()
    return redirect("reviews:index")

@login_required 
def comment_create(request, pk):
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
    return redirect('reviews:detail', review.pk)
  
def comment_delete(request, pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
        messages.warning(request, "댓글이 삭제되었습니다.")
    return redirect("reviews:detail", pk)
    
  

accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block body %}
회원목록

{% endblock body %}  

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}
<div class="row text-center py-5 my-5">
  <h1>로그인</h1>
</div>

<form action="" method="POST" class="form p-5 m-5">
  {% csrf_token %}
  {% bootstrap_form form %}

  <button class="btn text-white" style="background-color: #03C75A;" type="submit">로그인</button>
  <a href="{% url 'accounts:index' %}" class="btn btn-secondary m-1">취소</a>
</form>


{% endblock body %} 

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}
<div class="row text-center py-5 my-5">
  <h1>회원가입</h1>
</div>

<form action="" method="POST" class="form p-5 m-5">
  {% csrf_token %}
  {% bootstrap_form form %}

  <button class="btn text-white" style="background-color: #03C75A;" type="submit">등록</button>
  <a href="{% url 'accounts:index' %}" class="btn btn-secondary m-1">취소</a>
</form>


{% endblock body %}  

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %} 
<div class="row text-center py-5 my-5">
  <h1>글쓰기</h1>
</div>
  <!-- form : 사용자에게 양식을 제공하고
      값을 받아서(input : name, value)
      서버에 전송(form : action, method)-->
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form review_form %}
  {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}


{% block body %}
<h1>{{ review.title }}</h1>
<h4>{{ review.user.username }}</h4>
<h3>{{ review.created_at|date:"SHORT_DATETIME_FORMAT" }}</h3>
<p>{{ review.content }}</p>
{% if review.image %}
  <img src="{{ review.image.url }}" alt="review.image" width="400px" height="300px">
{% endif %}

<h4 class="my-3">댓글</h4>
{% if request.user.is_authenticated %}
<form action="{% url 'reviews:comment_create' review.pk %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form comment_form layout='inline' %}
  <br>
  {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endif %}

<hr>       

{% for comment in comments %}
{% if request.user == comment.user %}
    <p>{{ comment.user.username }} | {{ comment.content }} | <a href="{% url 'reviews:comment_delete' review.pk comment.pk %}">삭제</a></p>
    <hr>
{% endif %}  
{% empty %}
    <p>댓글이 없어요 ㅠ_ㅠ</p>

{% endfor %}



{% if request.user == review.user %}
  <a href="{% url 'reviews:update' review.pk %}">수정</a>
  <a href="{% url 'reviews:delete' review.pk %}">삭제</a>
{% endif %}

{% endblock %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
b
{% block body %}

{% if request.user.is_authenticated %}
    <a class="btn btn-primary my-3 float-right" href="{% url 'reviews:create' %}">글 쓰기</a>
{% endif %}

<div class="row">
  {% for review in reviews %}
  <div class="col-4">
    <div class="card">
      <img src="{{ review.image.url }}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{ review.title }}</h5>
        <p class="text-muted">{{ review.user.username }}</p>
        <a href="{% url 'reviews:detail' review.pk %}" class="btn btn-outline-primary my-3">보기</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock body %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}


{% block body %}

<h1>글수정하기</h1>

<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form review_form %}
  {% bootstrap_button button_type="submit" content="OK" %}
</form>
 


{% endblock %}

templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <title>Document</title>
</head>
<body>
  <nav class="navbar navbar-dark navbar-expand-lg" style="background-color: #04CF5C">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Never</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link text-white" href="#">{{ request.user }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'accounts:logout' %}">로그아웃</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'accounts:signup' %}">회원가입</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'accounts:login' %}">로그인</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {% block body %}
 
  {% endblock body %}  
</body>
</html>